site_name: Hypha Launcher Docs

repo_url: https://github.com/aicell-lab/hypha-launcher

theme: material

nav:
  - Home: index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
